### PR TITLE
Add DumpWinMD example

### PR DESCRIPTION
**Pull request by asklar**
This adds an example to dump the winmd structs/enums/interfaces/classes to stdout.
Hopefully this helps others who are looking to use this library :)

### CODE REVIEW

**Comment by asklar** [comment]
CC @DefaultRyan @kennykerr

**Comment by kennykerr** [comment]
Thanks Alexander. Unfortunately, we don't yet have a CI build and until we do I don't feel comfortable piling on code here. We also have a lot of code in [C++/WinRT](https://github.com/microsoft/cppwinrt) illustrating how to use the winmd parser so I'm not sure an example is that urgent, but feel free to take a stab at getting the CI build going.

**Comment by asklar** [comment]
@kennykerr I've added a CI in this PR, see results here https://github.com/asklar/winmd/runs/1171381840

**Review by kennykerr — APPROVED** [review]
Thanks!

**Pull request merged**
