### PR TITLE
Fix build using GCC

### LINKED ISSUE #27: view.h uses std::exchange but <utility> not included
`impl/winmd_reader/view.h` uses `std::exchange` but `<utility>` has not been explicitly included. It fails to build on GCC 12 / libstdc++ with `error: 'exchange' is not a member of 'std'`.

### PR DESCRIPTION
**Pull request by alvinhochun**
The first commit fixes warnings like the following when compiled on Linux GCC:

```
winmd/impl/winmd_reader/flags.h:306:28: error: declaration of ‘constexpr winmd::reader::CodeType winmd::reader::MethodImplAttributes::CodeType() const’ changes meaning of ‘CodeTy
pe’ [-fpermissive]
  306 |         constexpr CodeType CodeType() const noexcept
      |                            ^~~~~~~~
In file included from winmd/winmd_reader.h:6:
winmd/impl/winmd_reader/enum.h:188:16: note: ‘CodeType’ declared here as ‘enum class winmd::reader::CodeType’
  188 |     enum class CodeType : uint16_t
      |                ^~~~~~~~
```

(See also: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=41039, https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2019/p1697r0.html)

The second commit fixes https://github.com/microsoft/winmd/issues/27.

### CODE REVIEW

**Comment by kennykerr** [comment]
Unfortunately, there's currently no CI build for this repo. We need to validate the change in cppwinrt before merging.

**Comment by kennykerr** [comment]
Historically, the winmd reader was just a part of cppwinrt but then some other projects wanted to use it and here we are. It's a bit more work this way unfortunately.

**Comment by alvinhochun** [comment]
No problem, it is tested in the checks of this PR: https://github.com/microsoft/cppwinrt/pull/1239

**Comment by kennykerr** [comment]
Ran into some issues publishing the nuget package for this project. It may be simpler just to roll this into the cppwinrt repo (where it originated) and avoid the nuget dependency...

**Comment by alvinhochun** [comment]
These changes only affects building with GCC, so only the CMake build of cppwinrt will need the update. We can have the CMake build clone the latest source from this repo instead of downloading the nuget package.

MSVC and Clang don't require these changes, so the VS project can continue to use the current winmd nuget dependency.

This way we don't need to vendor the winmd headers into the cppwinrt repo. Does this sound good to you?

**Comment by kennykerr** [comment]
Sounds good.

cc @DefaultRyan in case he knows how to get the nuget package updated.

**Pull request merged**
